### ISSUE TITLE
插入中文记录数据库报错

### ISSUE THREAD

**Issue by logo008** [eedalong/Apache-IoTDB-Client-CSharp#82]
我插入如下带中文的内容：
var measures = new List<string> { "ts1", "ts2", "ts3", "ts4" };
var values = new List<object> { "我是中文S1111", "我是中文S2222", true, (int)123 };
var timestamp = 1;
var rowRecord = new RowRecord(timestamp, values, measures);
await session_pool.InsertRecordAsync("root.test_group.test_device", rowRecord);

数据库报错：
2022-11-09 16:50:24,614 [pool-44-IoTDB-Cluster-RPC-Client-15] WARN  o.a.i.d.u.ErrorHandlingUtils:61 - Status code: EXECUTE_STATEMENT_ERROR(400), operation: insertRecord failed
java.lang.ArrayIndexOutOfBoundsException: -26
        at org.apache.iotdb.db.qp.physical.crud.InsertRowPlan.fillValues(InsertRowPlan.java:463)
        at org.apache.iotdb.db.qp.physical.crud.InsertRowPlan.<init>(InsertRowPlan.java:112)
        at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl.insertRecord(TSServiceImpl.java:1525)
        at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$insertRecord.getResult(TSIService.java:3551)
        at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$insertRecord.getResult(TSIService.java:3531)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

数据库版本：0.13.3

**Comment by lausannel** [comment]
我们马上调查

**Comment by lausannel** [comment]
@logo008 问题原因已经找到了，是序列化TEXT类型的数据时编码长度错误，我们会在这个PR中 #83

**Comment by lausannel** [comment]
@logo008 我们已经在nuget上发布了最新的包~
