### ISSUE TITLE
[bug]:关于`算数运算符`异常的问题

### ISSUE THREAD

**Issue by MoeGuoH** [eedalong/Apache-IoTDB-Client-CSharp#90]
算数运算符 从0.13版本开始支持。但是我发现同样的语句如`SELECT A * 2 as A FROM root.texUquUa.A75NLL20m.A752bXW7`,在iotdb的cli客户端下正常执行，但是是用该项目客户端执行异常报错。

**Comment by lausannel** [comment]
我这边没能复现，请问能贴一下最小复现代码和server上的输出吗

**Comment by MoeGuoH** [comment]
测试代码片段:
```
using Apache.IoTDB;

using (var session_pool = new SessionPool("?????.???", 6667, "root", "root", 1024))
{
    await session_pool.Open(false);
    var version_result = await session_pool.ExecuteQueryStatementAsync("show VERSION ;");

    while (version_result.HasNext())
    {
        var a = version_result.Next();
        Console.WriteLine($"Version:{a.Values[0]}");
    }

    try
    {
        var result =
            await session_pool.ExecuteQueryStatementAsync(
                "select T * 2 from root.texUquUa.AqEwXs7Om.AcYs8rYkR limit 1;");
        while (result.HasNext())
        {
            var a = result.Next();
            Console.WriteLine($"T:{a.Timestamps},V:{a.Values[0]}");
        }
    }
    catch (Thrift.TException e)
    {
        Console.WriteLine(e);
    }
    
}
```

运行结果:
```
/Users/moe.guoh/Desktop/Test/ConsoleApp2/ConsoleApp2/bin/Debug/net6.0/ConsoleApp2 
Version:0.13.0
Thrift.TException: execute query failed
   at Apache.IoTDB.SessionPool.ExecuteQueryStatementAsync(String sql)
   at Program.<Main>$(String[] args) in /Users/moe.guoh/Desktop/Test/ConsoleApp2/ConsoleApp2/Program.cs:line 18
```
服务端运行错误日志:
```
2023-03-03 08:32:25,783 [pool-13-IoTDB-RPC-Client-52583] ERROR o.a.i.d.u.ErrorHandlingUtils:83 - Status code: 411, Query Statement: "select T * 2 from root.texUquUa.AqEwXs7Om.AcYs8rYkR limit 1;". executeQueryStatement failed
org.apache.iotdb.db.exception.query.LogicalOptimizeException: The value of SOFFSET (0) is equal to or exceeds the number of sequences (1) that can actually be returned.
	at org.apache.iotdb.db.qp.utils.WildcardsRemover.checkIfSoffsetIsExceeded(WildcardsRemover.java:140)
	at org.apache.iotdb.db.qp.strategy.optimizer.ConcatPathOptimizer.removeWildcardsInSelectPaths(ConcatPathOptimizer.java:133)
	at org.apache.iotdb.db.qp.strategy.optimizer.ConcatPathOptimizer.transform(ConcatPathOptimizer.java:72)
	at org.apache.iotdb.db.qp.Planner.optimizeQueryOperator(Planner.java:153)
	at org.apache.iotdb.db.qp.Planner.logicalOptimize(Planner.java:136)
	at org.apache.iotdb.db.qp.Planner.generatePhysicalPlanFromOperator(Planner.java:113)
	at org.apache.iotdb.db.qp.Planner.parseSQLToPhysicalPlan(Planner.java:63)
	at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl.executeQueryStatement(TSServiceImpl.java:652)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeQueryStatement.getResult(TSIService.java:2903)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeQueryStatement.getResult(TSIService.java:2883)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-03-03 08:32:26,101 [pool-13-IoTDB-RPC-Client-52585] INFO  o.a.i.d.s.b.ServiceProvider:214 - Session-47721953 is closing
```

使用服务下sbin/start-cli执行结果
```
---------------------
Starting IoTDB Cli
---------------------
 _____       _________  ______   ______
|_   _|     |  _   _  ||_   _ `.|_   _ \
  | |   .--.|_/ | | \_|  | | `. \ | |_) |
  | | / .'`\ \  | |      | |  | | |  __'.
 _| |_| \__. | _| |_    _| |_.' /_| |__) |
|_____|'.__.' |_____|  |______.'|_______/  version 0.13.0


IoTDB> login successfully
IoTDB> select T * 2 from root.texUquUa.AqEwXs7Om.AcYs8rYkR limit 1;
+------------------------+---------------------------------------+
|                    Time|root.texUquUa.AqEwXs7Om.AcYs8rYkR.T * 2|
+------------------------+---------------------------------------+
|2022-08-31T11:36:30.914Z|                                   67.1|
+------------------------+---------------------------------------+
Total line number = 1
It costs 0.264s
IoTDB>
```

**Comment by lausannel** [comment]
好的，我这边调查一下

**Comment by lausannel** [comment]
目前原因不太清楚，不过建议先升级到1.0版本，0.13版本基本已经停止维护了
